resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: next-app-env
  literals:
    - NODE_ENV=development
    - services__api__http__0=http://api:8080
    - PORT=8000
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=next-app

